### ISSUE TITLE
Add shorthands support for `grid-area`

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/griffel#120]
`grid-area` is a shorthand for 4 different values, engineers perhaps use just the `grid-area` shorthand and even don't know what that should be expanded to.
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-area

Add `shorthands.gridArea()`.

**Comment by miroslavstastny** [comment]
We should go through all `grid` related shorthands to analyze what actually needs to be done.

**Comment by layershifter** [comment]
Was done in #130.
