### ISSUE TITLE
improve debugging for nodes with many classes

### ISSUE THREAD

**Issue by heho** [microsoft/griffel#122]
If there are slots that produce large amounts of classes, for example when using @rules and several selectors, debugging can get quite tiresome since the DOM is cluttered with classes and when looking at one Node one sometimes has to work through quite a lot of classes to find what they are looking for. I have no real feasable solution at this point for this. Maybe allowing disabling the atomic aspect for development builds could work.

**Comment by layershifter** [comment]
Devtools are publish in [Chrome store](https://chrome.google.com/webstore/detail/griffel-devtools/bejhagjehnpgagkaaeehdpdadmffbigb). Please check it and feel free to leave feedback in [discussions](https://github.com/microsoft/griffel/discussions).
