### ISSUE TITLE
react griffel reevaluation of resolveStyleRulesForSlots

### ISSUE THREAD

**Issue by heho** [microsoft/griffel#125]
As far as I understand the react bindings expose the makeStyle function from core in a way that does will cause reevaluation of the resolveStyleRulesForSlots function on rerender. This does not seem sensible to me as it could be evaluated earlier as it does not depend on anything from inside the function and seems to be somewhat expensive.

**Comment by layershifter** [comment]
Sorry, but I don't understand the idea. Can you please clarify your expectations?
