### ISSUE TITLE
@griffel/jest-serializer doesn't seem to work

### ISSUE THREAD

**Issue by ScubaDaniel** [microsoft/griffel#153]
I'm following the directions provided on the following README, but it doesn't do anything: https://github.com/microsoft/griffel/tree/main/packages/jest-serializer

We're using jest "^27.5.1" and ts-jest "^27.1.3".

The output still has all the generated class names.

**Comment by ScubaDaniel** [comment]
I've also tried using the plugin the same way as your tests, but that doesn't work either:

```ts
import { print, test } from "@griffel/jest-serializer";

expect.addSnapshotSerializer({ print, test });
```

Could you provide more direction on how to use this?

**Comment by layershifter** [comment]
Can you please provide a minimal repro case on how it's configured/is used?

I created a minimal sandbox on Stackblitz (https://stackblitz.com/edit/node-ioqsq2?file=jest.config.js,src%2FComponent.test.tsx) and it works as expected - snapshots don't have classes in output.

**Comment by layershifter** [comment]
@ScubaDaniel I am closing this for housekeeping, but will reopen if there will be additional details.
