### ISSUE TITLE
webpack-extraction-plugin: Use with NextJS

### ISSUE THREAD

**Issue by Dwlad90** [microsoft/griffel#154]
Hi, I was trying to use this package with nextJS using the mini-css-extract-plugin built-in but in its construction I get the following error:

Global CSS cannot be imported from files other than your Custom <App>. Due to the Global natureof stylesheets, and to avoid conflicts, Please move all first-party global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).

Sandbox: https://codesandbox.io/s/withered-firefly-2ff6m8

I have to add the plugin with certain parameters to the pipeline so it’ll work properly:

new MiniCssExtractPlugin({ // without these Next.js will look for the generated stylesheets from the wrong place filename: "static/chunks/[chunkhash].css", chunkFilename: "static/chunks/[chunkhash].css", ignoreOrder: true, })

Sandbox: https://codesandbox.io/s/hardcore-mendel-9xywyx

Maybe you have an idea how can I use a built-in plugin?

**Comment by layershifter** [comment]
@Dwlad90 FYI: I have a vacation for a week, but I will check it after.

**Comment by layershifter** [comment]
@Dwlad90 thanks for great repros. Complains about import order from `mini-css-extract-plugin` (silenced with `ignoreOrder`) are also not great 🫤

It's great that these is a workaround, but we will look into it and find a proper solution or document it.

**Comment by Dwlad90** [comment]
@layershifter I will be grateful for a more proper solution.

It's a temporary solution that allows you to extract CSS with NextJS. This is what the native style loader of NextJS does, [proof](https://github.com/vercel/next.js/blob/0f99768f9811fdf027a083471bd2a435f6207f4a/packages/next/build/webpack/config/blocks/css/index.ts#L499).

PS, without the ignoreOrder property, there are a lot of warnings at build time.
