### ISSUE TITLE
core: the default sort order for media queries should be author order

### ISSUE THREAD

**Issue by spmonahan** [microsoft/griffel#155]
#141 added a feature to allows media queries to be sorted. However, [the default sort implementation](https://github.com/microsoft/griffel/blob/fc8266bace8f4de09469ddaf929ff0bf990274a7/packages/core/src/renderer/createDOMRenderer.ts#L34) is string comparison which breaks down for common breakpoint media queries that depend on insertion order like:

```js
"@media (min-width: 488px)": {
  width: "816px"
},
"@media (min-width: 1024px)": {
  width: "816px"
},
"@media (min-width: 1366px)": {
  width: "1164px"
},
"@media (min-width: 1920px)": {
  width: "1564px"
}
```

Because the default sort function is a string comparison these media queries are inserted in the following order:

1. 1024px
2. 1336px
3. 1920px
4. 488px

<img width="790" alt="media_query_order" src="https://user-images.githubusercontent.com/93940821/176758014-fd28b3d5-ae2e-4475-9eda-76ff1cf65a1f.png">

Which leads to incorrect behavior based on the order in which the styles was authored.

This can be worked around by using a min-max range in the media queries but I think a better approach is for the default sort implementation to respect the order in which the media queries are authored.

Example workaround:

```js
"@media (min-width: 488px) and (max-width: 1024px)": {
  width: "816px"
},
"@media (min-width: 1024px) and (max-width: 1366px)": {
  width: "816px"
},
"@media (min-width: 1366px) and (max-width: 1920px)": {
  width: "1164px"
},
"@media (min-width: 1920px)": {
  width: "1564px"
}
```

I've made a Codesandbox to demonstrate this behavior: https://codesandbox.io/s/griffel-media-query-sort-order-gkt1n9

**Comment by ling1726** [comment]
It's hard to say what is 'author order' because once there are multiple invocations of `makeStyles` with media queries then this quickly breaks down. Here is an example where 'author order is not deterministic': https://codesandbox.io/s/media-order-forked-42wf1v?file=/src/App.js

**Comment by ling1726** [comment]
A user defined order  tha is deterministic can be quite easily achieved with the below code.

```ts
const mediaQueryOrder = [
  "(min-width: 488px) and (max-width: 1024px)",
  "(min-width: 1024px) and (max-width: 1366px)",
  "(min-width: 1366px) and (max-width: 1920px)",
  "(min-width: 1920px)",
]

const compareMediaQueries = (a: string, b: string) => {
  return mediaQueryOrder.indexOf(a) - mediaQueryOrder.indexOf(b);
}

createDOMRenderer(document, { compareMediaQueries });
```

However I think some built-in comparators would be very helpful for common scenarios like this (screen width)

**Comment by spmonahan** [comment]
Definitely agree that some built-in comparators would be really great plus more documentation about this feature.

Thanks for the example. I understand that no matter what our default we'll hit cases where things don't "just work" but it seems to me that with the current default a basic use case with a single `makeStyles` invocation failing with `min-width` queries will feel like a bug to most users.

Is there a default we can apply that will maintain determinism for multiple `makeStyles` calls and maintain the "author order" within a given `makeStyles` call?

**Comment by ling1726** [comment]
> Is there a default we can apply that will maintain determinism for multiple makeStyles calls and maintain the "author order" within a given makeStyles call?

No. That's what I was trying to illustrate with the example. We can maintain author order within a single makeStyles call, but due to the nature of makeStyles usage, there's no real way to know anything about order until style render time. Each makeStyles call is coupled with component and once components start getting moved around different places, you risk changing the existing order.

It's what you would do with a simple comparator like the one below that's based in 'appearance order' which will satisfy the 'author order' requirement but not the requirement for multiple calls.

```ts`
const compareMediaQueries = (a, b) => 1;
```

**Comment by miroslavstastny** [comment]
There should be docs in both griffel and FUI.
Think about having a better default.
