### ISSUE TITLE
core: `DEFINITION_LOOKUP_TABLE` causes issues when multiple versions of @griffel/core are present

### ISSUE THREAD

**Issue by layershifter** [microsoft/griffel#159]
`DEFINITION_LOOKUP_TABLE` is a singleton used by `mergeClasses()` to merge classes sequences deterministically. The problem comes when there are multiple versions of `@griffel/core` that use different by reference `DEFINITION_LOOKUP_TABLE` constants.

It's more or less the same problem that React has with `.createContext()` calls (see https://github.com/facebook/react/issues/13346).

Repro on Stackblitz: https://stackblitz.com/edit/node-zerdgf?file=index.js

**Comment by miroslavstastny** [comment]
Reported by partners (multiple versions of griffel in a bundle). The current idea is to have the DLT on `window`.

**Comment by changyoungoh** [comment]
> Reported by partners (multiple versions of griffel in a bundle). The current idea is to have the DLT on `window`.

If using `window` to avoid singleton problem, wouldn't there be a problem when using SSR?

**Comment by layershifter** [comment]
> > Reported by partners (multiple versions of griffel in a bundle). The current idea is to have the DLT on `window`.
> 
> If using `window` to avoid singleton problem, wouldn't there be some issues when using SSR?

In SSR we will use `global` or will find another approach. We don't plan to regress in SSR support.
