### ISSUE TITLE
`@griffel/webpack-loader` doesn't use specified babel preset to parse input source file

### ISSUE THREAD

**Issue by yume-chan** [microsoft/griffel#195]
With the updated instructions in #194, `@griffel/webpack-loader` still doesn't work with TypeScript files.

In further investigation, it throws error here:

https://github.com/microsoft/griffel/blob/8d663649fdf12b4fa939b9158bef03660ae03d6d/packages/webpack-loader/src/transformSync.ts#L21-L30

As it always uses default babel configuration to parse the input code.

Existing tests all passed because they don't use any TypeScript-only language features, so Babel just parse them as JavaScript.

It would be an easy fix, simply adding `...options.pluginOptions.babelOptions,` into the object. However, I could find how to test it: if source code contains TypeScript-specific syntax, the loader outputs them as-is, so Webpack in current test infrastructure doesn't understand them.

**Comment by layershifter** [comment]
To clarify,`babelOptions` are used only for module evaluation when we parse imported files, for example:

```ts
import { makeStyles } from "@griffel/react";
import { tokens } from '../tokens'
// Will be used for this 👆

const useClasses = makeStyles({
  container: {
    backgroundColor: tokens.backgroundColor,
  }
})
```

It's expected that our loader will run after existing loaders (`babel-loader`, `ts-loader`, `swc-loader`, etc.) so code in a file will be already transformed. I modified the PR (#194) to do `config.module.rules.unshift` instead as it's expected.

The single problem there is that we need to get a fix from upstream to handle SWC helpers (https://github.com/callstack/linaria/pull/1046).

**Comment by yume-chan** [comment]
Confirmed using `unshfit` works in all scenarios I can imagine. Thanks!
