### ISSUE TITLE
`Slot` performance issue

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/griffel#198]
VS Code can do auto-import when users try to use a module that is not imported. Here comes my problem: even auto-import of React module could happen immediately, but every time I try to auto import the type `Slot`, I must wait for several seconds. Is this type bigger or more complex than the whole React?

**Comment by AkiraVoid** [comment]
And, after imported `Slot`, the IntelliSence will also be very slow (loading for seconds). It's not caused by extensions of VS Code, I disabled all extensions and this problem is still remain (better than before, but still worse). Also, I don't think this is a VS Code problem because everything is fine before I imported `Slot`.

**Comment by layershifter** [comment]
We don't have a type named `Slot`, can you please clarify what do you mean?

**Comment by AkiraVoid** [comment]
So `Slot` is only in `@fluentui/react-components`? I thought it is a Griffel feature.

**Comment by AkiraVoid** [comment]
So `Slot` is only in `@fluentui/react-components`? I thought it is a Griffel feature.

**Comment by AkiraVoid** [comment]
OK, I see. It is exposed by `@fluentui/react-utilities`, I will close this issue and move it to Fluent UI repo.
