### ISSUE TITLE
Cannot use `background-position`

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/griffel#203]
Griffel does not support `background-position`. That is expected as it is a CSS shorthand. We are supposed to use `background-position-x` and `background-position-y` longhands instead.

## Shorthand works
The problem is with
```css
background-position: center bottom 10px;
```
It works consistently across browsers:

| Chrome 104 | Firefox 104 | Safari 15.6.1 |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/9615899/187713991-c53fe0b4-04f5-414d-9386-99499909ef93.png) | <img width="299" alt="image" src="https://user-images.githubusercontent.com/9615899/187714505-879097bd-31e6-4255-8da8-6ccf09fced35.png"> | <img width="299" alt="image" src="https://user-images.githubusercontent.com/9615899/187714731-0cd6593b-87f3-4096-9c9a-a668cab4fb1e.png">

Codesandbox: https://codesandbox.io/s/empty-wood-1m917y

## Longhands broken in Chrome 104

Once we expand that to longhands:
```css
background-position-x: center;
background-position-y: bottom 10px;
```

The result is still the same in Firefox and Safari but breaks in Chrome:
| Chrome 104 | Firefox 104 | Safari 15.6.1 |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/9615899/187715478-7678708a-cd2a-401a-93f9-21b2fae247d9.png) |<img width="301" alt="image" src="https://user-images.githubusercontent.com/9615899/187715580-f59ec1b6-4a5e-4f4f-a39d-6a31ebaef861.png"> | <img width="299" alt="image" src="https://user-images.githubusercontent.com/9615899/187715752-710187a3-c15e-4139-bc51-c74d2789f9bc.png"> |

Codesandbox: https://codesandbox.io/s/vibrant-heyrovsky-7ezu6h

**Comment by miroslavstastny** [comment]
Chrome shows an error in devtools:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/9615899/187716229-8c5adf8e-8ee4-49e8-88fe-358c53f18bad.png">

**Comment by nadnad** [comment]
Chromium issue for the longhand bug: https://bugs.chromium.org/p/chromium/issues/detail?id=610627&q=background-position-y&can=2

**Comment by layershifter** [comment]
@miroslavstastny `backgroundPosition` can be used now as we support CSS shorthands now, see #531.
