### ISSUE TITLE
react: missing definition for "children" in RendererProviderProps

### ISSUE THREAD

**Issue by Kerryliu** [microsoft/griffel#214]
React 18+ requires `children` to be explicitly defined:
https://stackoverflow.com/a/59106817/7361755

https://github.com/microsoft/griffel/blob/ef665ab8dbc42c4db6625144357041f55e78c46e/packages/react/src/RendererContext.tsx#L5-L13

**Comment by layershifter** [comment]
@Kerryliu thanks for reporting, would you mind to create a PR to fix it? 🐱

**Comment by Kerryliu** [comment]
Done! :)
