### ISSUE TITLE
babel-preset: produces invalid import for `filter: url(#a)`

### ISSUE THREAD

**Issue by yume-chan** [microsoft/griffel#233]
Input:

```js
import { makeStyles } from "@griffel/core";

export const useClasses = makeStyles({
  root: {
    filter: `url(#a)`
  }
})
```

Output:

```js
import _asset from "./#a";
import { __styles } from "@griffel/core";
export const useClasses = __styles({
  "root": {
    "Bhu2qc9": "f1rurakv"
  }
}, {
  "d": [`.f1rurakv{-webkit-filter:url(src/#a);filter:url(${_asset});}`]
});
```

`filter: url(#a)` refers to a `filter` element with ID `a` in an SVG element, it's not an asset that needs to be imported, so it should output as is.

Also, even if `#a` is an asset, `-webkit-filter:url(src/#a)` should be `-webkit-filter:url(${_asset})`.

Complete repro: https://github.com/yume-chan/griffel-filter-url

**Comment by layershifter** [comment]
@yume-chan thanks for the complete report 👍  I think that an additional condition there could fix it:

https://github.com/microsoft/griffel/blob/ebe44fdd9c34a87a4106c95c5b47f5719c215e8f/packages/babel-preset/src/assets/normalizeStyleRules.ts#L30-L32
