### ISSUE TITLE
Allow React 18 in peerDependencies

### ISSUE THREAD

**Issue by nahumzs** [microsoft/griffel#262]
Fluent UI library has already merged, and I would think soonish to release support for react 18; any chance griffle will update the peer dependency sooner and make it compatible with react 18?

https://github.com/microsoft/fluentui/issues/22241

https://github.com/microsoft/griffel/blob/main/packages/react/package.json#L16

**Comment by layershifter** [comment]
Hey, there are some improvements that we need to make for React 18 (#40). But overall - it works, so there are no reasons to not allow React 18 in `peerDependencies`. I will create a PR.

**Comment by layershifter** [comment]
Released in `@griffel/react@1.4.2`.
