### ISSUE TITLE
core: add support for @container

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/griffel#270]
`@container` is supported in the latest Chrome, Edge and Safari.
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries

**Comment by benpender** [comment]
Very interested in support for this!

**Comment by sjwilczynski** [comment]
@layershifter do you know when this could be added. We would love to use container queries in one of M365 components :)

**Comment by layershifter** [comment]
@sjwilczynski someone wanted to implemented during FHL, so we postponed this task. I put it to our next sprint.
