### ISSUE TITLE
Griffel webpack-loader incompatible with exports maps that use `import` conditions.

### ISSUE THREAD

**Issue by dzearing** [microsoft/griffel#272]
## Expected:

Packages can have exports maps without CJS modules and use the griffel loader.

## Resulted:

enhanced-resolve can't find modules

## Details:

I see this code in `webpackLoader.ts`:

```ts
  const resolveOptionsDefaults: webpack.ResolveOptions = {
    conditionNames: ['require'],
    extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
  };

  const resolveSync = enhancedResolve.create.sync({
    ...resolveOptionsDefaults,
    alias: resolveOptionsFromWebpackConfig.alias,
    modules: resolveOptionsFromWebpackConfig.modules,
    plugins: resolveOptionsFromWebpackConfig.plugins,
  });
```

The `conditionNames` value is hardcoded to `require` condition. I hit bundle failures in the bohemia repo as soon as a package added this exports map:

```js
  "exports": {
    ".": {
      "types": "./lib/index.d.ts",
      "source": "./src/index.ts",
      "import": "./lib/index.js",
      "default": "./lib/index.js"
    }
```

Deleting the `import` condition made griffel not complain about missing modules. I expect that `import` presence seems to skip `default` fallback somehow. But errors look like:

```bash
Error: Package path . is not exported from package D:\git\...\app-ux (see exports field in D:\git\...\app-ux\package.json)
    at D:\git\office-bohemia-2\node_modules\enhanced-resolve\lib\ExportsFieldPlugin.js:104:7      
    at Hook.eval [as callAsync] (eval at create (D:\git\...\node_modules\enhanced-resolve\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Resolver.doResolve (D:\git\...\node_modules\enhanced-resolve\lib\Resolver.js:432:16)
```

**Comment by layershifter** [comment]
I had an offline chat with @dzearing, I can't repro the issue. We agreed that David will provide more reproduction steps on it.

**Comment by layershifter** [comment]
Going to close for housekeeping. If we will get a repro in a Github repository or StackBlitz, would be happy to check and re-open.
