### ISSUE TITLE
typescript makeStyles  doesn't accept local `string` css variables | Type 'string' is not assignable to type 'GriffelStyle'.

### ISSUE THREAD

**Issue by pukingrainbows** [microsoft/griffel#286]
Hello, Griffle team, under the [limitations](https://griffel.js.org/react/guides/limitations) page is detail that a workaround for runtime styles is to use local CSS variables. 

Unfortanely typescript is complaining about makeStyles types `Type 'string' is not assignable to type 'GriffelStyle'.`

I wonder if this is a bug or am I doing something incorrectly? 🙇‍♂️

```js
const usePixelStyle = makeStyles({
  width: "var(--pkr-pixel-width)",
  height: "var(--pkr-pixel-height)",
})

```

<img width="557" alt="image" src="https://user-images.githubusercontent.com/50537727/205468219-54279db7-85df-457a-878e-8cf18a0627a4.png">

<img width="550" alt="image" src="https://user-images.githubusercontent.com/50537727/205468214-861438ad-03b5-45e5-90fe-ac68024b1b3e.png">

**Comment by pukingrainbows** [comment]
This is my mistake, I forgot to add a "className"

```js	
const usePixelStyle = makeStyles({
	root: {
		width: "var(--pkr-pixel-width)",
  		height: "var(--pkr-pixel-height)",
	}
})
```

that's valid, forgot to add "root" or any other "className," closing it but keeping it in case someone else makes the same mistake.

**Comment by layershifter** [comment]
@pukingrainbows can you please check #287? Is it clearer now?
