### ISSUE TITLE
Do not add CSS shorthands in runtime

### ISSUE THREAD

**Issue by layershifter** [microsoft/griffel#29]
We don't allow to use CSS shorthands:
https://github.com/microsoft/griffel/blob/b4c7acc77e5e7b4883ca32249418a3d93dc43e77/packages/core/src/types.ts#L5-L49

We should implement something in runtime to prevent adding rules with shorthands. Currently shorthands usage produces TS errors, but rules are still inserted to DOM. That creates confusion and feeling that something is wrong with typings.

- This should be based on typings that we have
- The runtime check should be development (non-production) to avoid contributions to bundle size

#### Expected behavior

```tsx
import { makeStyles } from "@griffel/react";

const useClasses = makeStyles({
  root: {
    // ⏭ "background" is not inserted to DOM & a warning is produced (currently inserted)
    // 💥 produces TS error (already done)
    background: "red"
  }
});
```

**Comment by Aloento** [comment]
I have a question, why don't we support this writing style?

**Comment by layershifter** [comment]
@Aloento you find out more details in that comment, https://github.com/microsoft/griffel/issues/30#issuecomment-1045959297. If you have questions, let's continue there.

**Comment by Aloento** [comment]
Maybe your document seems like didn't mention that.
and I don't know why I can't scroll down your docs page

https://user-images.githubusercontent.com/11802769/164110688-ea06a010-fefc-41e1-a1dd-b6f58553da75.mp4

.

**Comment by layershifter** [comment]
> Maybe your document seems like didn't mention that.
> and I don't know why I can't scroll down your docs page

This looks really strange. Can you please share details about your environment? OS, browser?

**Comment by Aloento** [comment]
@layershifter Microsoft Edge 100.0.1185.44, Windows 11 64bit

**Comment by Aloento** [comment]
> @Aloento you find out more details in that comment, [#30 (comment)](https://github.com/microsoft/griffel/issues/30#issuecomment-1045959297). If you have questions, let's continue there.

https://github.com/microsoft/fluentui/blob/master/rfcs/react-components/convergence/no-css-shorthands-in-make-styles.md
