### ISSUE TITLE
Document why CSS shorthands are forbidden

### ISSUE THREAD

**Issue by layershifter** [microsoft/griffel#30]
`README` file for [`@griffel/react`](https://github.com/microsoft/griffel/tree/main/packages/react) should contain limitations section.

It should include explainer why CSS shorthands are forbidden and reference shorthand functions.

**Comment by layershifter** [comment]
> No support for shorthands came as a big shock. I'd definitely want to clearly understand why shorthands are forbidden before depending on the version of `@fluentui/react-components` that uses griffel.

Hey, thanks for feedback. We understand consequences and choose predictability as we cannot expand CSS shorthands properly. You can more context in the [matching RFC](https://github.com/microsoft/fluentui/blob/master/rfcs/react-components/convergence/no-css-shorthands-in-make-styles.md).

> This adds a huge amount of verbosity to one of my projects in a way that'd impact readability of the code. For example, border: '1px solid var(--colorNeutralForeground)' must become:

Totally agree, writing 12 CSS rules for a single border is not okay, that's why we have already introduced [some helpers](https://github.com/microsoft/griffel/tree/main/packages/core/src/shorthands):

```tsx
import { shorthands } from '@griffel/react';
// 👇 These helpers are also re-exported in Fluent UI itself
// import { shorthands } from '@fluentui/react-components';

makeStyles({
  root: {
    backgroundColor: 'red',
    display: 'flex',
    ...shorthands.border('1px', 'solid', 'red'),
    ...shorthands.margin('5px'),
    ...shorthands.padding('10px', '2px')
  }
})
```

The problem is that these functions are not documented (and reasoning, too). We will work on it.

**Comment by thure** [comment]
Thank you for sharing the RFC, I understand the motivation for this design choice better now.

Offering a shorthands helper will certainly go a long way toward ameliorating the ergonomic consequences of this design choice, I'm glad to hear those will be made available alongside `makeStyles`.
