### ISSUE TITLE
Next.js13 & React Server Components

### ISSUE THREAD

**Issue by taishinaritomi** [microsoft/griffel#303]
Hello everyone at griffel!
I have just succeeded in getting ["Build time transform CSS in JS"](https://github.com/taishinaritomi/kaze-style/tree/main/playground/next-app-dir) working with Next.js13 & React Server Components.
I would like to share how to do it.
May I share it?

**Comment by layershifter** [comment]
Hey, we have an issue for that problem (#266). I didn't have time to dig into it yet, so feel free to post share results/open a PR 👍

**Comment by taishinaritomi** [comment]
Thank you.
I will do it from tomorrow.
