### ISSUE TITLE
Webpack plugin inserts raw CSS into JS code

### ISSUE THREAD

**Issue by NotWoods** [microsoft/griffel#307]
<img width="603" alt="Screenshot of source code showing minified CSS at the bottom of a JS script, with no quotes to escape it." src="https://user-images.githubusercontent.com/1782266/211086361-a00b7a42-6db0-4ca0-aac2-6172a30ed4e3.png">

With the latest Fluent UI (9.8.0) and Griffel (1.5.2) versions, we noticed that extracted CSS is now being inserted into the bottom of our JS script. As a result, the JS fails to run since it contains invalid code (ie: parser error on the `.` from the first CSS selector).

This is blocking us moving to the latest Fluent version.

**Comment by jurokapsiar** [comment]
Hi  @NotWoods, thank you for reporting. Can you please provide repro steps for the issue? We have not observed this with other partners, I would like to understand how is your case different.

**Comment by layershifter** [comment]
I debugged it in the repo, it's a problem with tooling there. @NotWoods I will share details with you.
