### ISSUE TITLE
vite: Add plugin for Vite

### ISSUE THREAD

**Issue by zoontek** [microsoft/griffel#33]
Hello 👋 

This project seems very promising! Do you have plan to support Vite with a custom plugin?

Documentation: https://vitejs.dev/guide/api-plugin.html
`vanilla-extract` plugin (for reference): https://github.com/seek-oss/vanilla-extract/tree/master/packages/vite-plugin

**Comment by layershifter** [comment]
Hey, yes we plan to have more integrations with bundlers and frameworks. Having Vite plugin is something that we want.

The implementation should be similar to the existing Webpack loader: call Babel and reuse bundler's module resolution. I haven't checked Vite docs yet and don't know what APIs are exposed, but it should it be doable.

**Comment by layershifter** [comment]
The closest example/reference for us is [`@linaria/rollup`](https://github.com/callstack/linaria/blob/master/packages/rollup/src/index.ts), but it has the problem that I mentioned (https://github.com/callstack/linaria/issues/888). In fact, we need something similar in Rollup/Vite:

https://github.com/microsoft/griffel/blob/b4c7acc77e5e7b4883ca32249418a3d93dc43e77/packages/webpack-loader/src/webpackLoader.ts#L69-L80

**Comment by layershifter** [comment]
Okay, it seems that [`this.resolve()`](https://rollupjs.org/guide/en/#thisresolve) in Rollup is close to what we need 😸

**Comment by zoontek** [comment]
I will check when I have some time 🙂

**Comment by layershifter** [comment]
> I will check when I have some time 🙂

@zoontek thanks. FYI: I will cleanup my branch and will post as a draft PR on the next week.

**Comment by SahilTara** [comment]
Just wanted to bump on this issue since the linaria pr linked seems to have been merged.

**Comment by layershifter** [comment]
@SahilTara indeed, but we will need to move to Linaria v4 first (#184).

**Comment by layershifter** [comment]
> Any update on the vite plugin?

As [wyw-in-js](https://github.com/Anber/wyw-in-js) is out, I can rollout the plugin finally 🎉 

I reworked original PR (#41) and it can be shipped once the issue will be fixed (https://github.com/Anber/wyw-in-js/issues/27). As @Anber will be offline for some time, I expect that we will be able to ship it after NY.

**Comment by layershifter** [comment]
FYI #41 was merged and plugin will be available on NPM today. It does not support CSS extraction, yet (#494).
