### ISSUE TITLE
core: shorthands for padding-inline/padding-block/margin-inline/margin-block

### ISSUE THREAD

**Issue by KagamiChan** [microsoft/griffel#341]
Hi, I'd like to ask to add shorthands and checks for padding-inline/padding-block/margin-inline/margin-block, which are padding and margin under the context of possible different writing modes. This would be essential for building inclusive UI.

reference: https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline

**Comment by layershifter** [comment]
@KagamiChan that would be great. To get proper typings we need to get https://github.com/frenic/csstype/issues/93 resolved i.e. `csstype` should be released. After that we can update related shorthands/longhands 👍
