### ISSUE TITLE
core: no type error for shorthand style nested in template literal selector

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/griffel#352]
In [this codesandbox](https://codesandbox.io/s/amazing-euclid-pu5k2v?file=/src/App.tsx), I have style 

```tsx
const useClasses = makeStyles({
  App: {
    fontFamily: "sans-serif",
    // [`& .test-button`]: {
    [`& .${buttonClassName}`]: {
      textDecoration: "none"
    }
  }
});
```
`textDecoration` is shorthand, it should fail and I should get type error, but I didn't get any. There's no error in console either.
The interesting thing is that, if I use a plain selector (like the commented out line), instead of the selector with template literal, I get type error as expected

**Comment by layershifter** [comment]
This produces a TS error with TS 5.2 and latest Griffel:

- [TS playground](https://www.typescriptlang.org/play?ts=5.2.2#code/JYWwDg9gTgLgBAbziAhgawKYGUYE8A2GAznAL5wBmUEIcARAAIDmUwFFG+A9FBigMYw6AbgBQo-hAB2ReACMArjBjSAwvhREiAORQgMcALxwA5BQgQT4jAA9IsOJJnwFRDOs1uSx1JhwFiAAoEUTg4AEEwMAAuRFCwymkYADE9YHxcWLoiFBkAWjdWCjoAGniwri44AG0AAwAyOAA6GGIYPMVlaVqAXViQhJqG5oASBE6VKQ8tXX1SXv7yhNabGAARDEkoFBhgaSypaQw6JdJ4s9IASmEgA)
- [CodeSandbox](https://codesandbox.io/s/young-architecture-g8z4wy?file=/src/App.tsx)

I don't see how it can be solved for lower versions of compiler as it's how TS worked 😶

- [TS5.1](https://www.typescriptlang.org/play?ts=5.1.6#code/GYVwdgxgLglg9mABAQwM6oKYCcoBUCeADhgBSpT4A2GAXIgELJYCUdjWiA3gFCKJYYoILEnJUMAbm4BfbtwrEGTRAF4uvFJUoB+OuSwwwAcxlyICcogBGIKFAQBhSmlQA5ZAFsMqxAHJgcHC+Ui7YeESkPHwA2gAGAGSIAHQAJJw2do7O6O5e0rEAunRRfIhQGAAeUAAiGOZYyLAIdL5gCBi+ADQa0t3SzBJAA) - passes 🔴 
- [TS5.2](https://www.typescriptlang.org/play?ts=5.2.2#code/GYVwdgxgLglg9mABAQwM6oKYCcoBUCeADhgBSpT4A2GAXIgELJYCUdjWiA3gFCKJYYoILEnJUMAbm4BfbtwrEGTRAF4uvFJUoB+OuSwwwAcxlyICcogBGIKFAQBhSmlQA5ZAFsMqxAHJgcHC+Ui7YeESkPHwA2gAGAGSIAHQAJJw2do7O6O5e0rEAunRRfIhQGAAeUAAiGOZYyLAIdL5gCBi+ADQa0t3SzBJAA) - throws 🟢
