### ISSUE TITLE
Styles converter not dealing with flex shorthand properly

### ISSUE THREAD

**Issue by mbman** [microsoft/griffel#360]
It converts style `flex: "0 0 auto"` into invalid Griffel shorthand `shortands.flex("0", "0", "auto")`.
This is invalid because  Griffel expects first 2 parameters to be numbers by type check and if not it bails out from generating that style.

**Comment by YuanboXue-Amber** [comment]
The converter is actually not in this repo. I will create an ado task when I'm at my computer and then close this issue

**Comment by YuanboXue-Amber** [comment]
ADO task 2995243 created
