### ISSUE TITLE
Is SCSS parent-selector syntax supported?

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/griffel#376]
Does griffel support [parent selectors](https://sass-lang.com/documentation/style-rules/parent-selector) like `&:hover` or `&.abc` ?

I see there is following code example in documentation

```ts
import { makeStyles } from '@griffel/react';

const useClasses = makeStyles({
  root: {
    ':active': { color: 'pink' },
    ':hover': { color: 'blue' },
    // :link, :focus, etc.

    '.foo': { color: 'black' },
    ':nth-child(2n)': { backgroundColor: '#fafafa' },

    '@media screen and (max-width: 992px)': { color: 'orange' },
    '@container (max-width: 992px)': { color: 'orange' },
    '@container foo (max-width: 992px)': { color: 'orange' },
    '@supports (display: grid)': { color: 'red' },
    '@layer utility': { marginBottom: '1em' },
  },
});
```

I assume `':active'` is something similar to `&:active` in SCSS. Then is there possibly counterpart to SCSS `&.class` existing in griffel?

**Comment by layershifter** [comment]
@chenxinyanc if I correctly understood, you're looking for `:global()`, https://griffel.js.org/react/api/make-styles#global-selector

Does it solve your problem?

**Comment by chenxinyanc** [comment]
Yeah that's exactly what I'm looking for. I wasn't aware of the documentation page somehow 😂 until I see the link on the repo profile.

I have only been aware of the ["Read more" link](https://github.com/microsoft/griffel/tree/main/packages/react) in README.md.

![image](https://github.com/microsoft/griffel/assets/50703224/b2966d1d-471e-4b1f-9baa-c5283e6f0b12)

**Comment by layershifter** [comment]
README also mentions it, BTW https://github.com/microsoft/griffel/tree/main/packages/react#pseudo--class-selectors-at-rules-global-styles

But it's a good call, we need to link website in README, too 👍

**Comment by layershifter** [comment]
Closing as the question was answer, @chenxinyanc FYI I also update README to include more links:

<img width="362" alt="image" src="https://github.com/microsoft/griffel/assets/14183168/d5495ad8-8942-4620-b476-6222203c64d9">
