### ISSUE TITLE
feature(core): `transform` is expanded to 3 different vendor prefixes

### ISSUE THREAD

**Issue by ling1726** [microsoft/griffel#379]
When using the css [transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) property, Griffel will expand this to include vendor prefixing for:

* webkit
* moz
* ms (i.e 11 I guess?)

This results in a style rule that will have 4 times its length (including the actual transform) and negatively impacts bundlesize

**Comment by layershifter** [comment]
Our base browser support matrix matches that the matrix in Fluent UI v9, https://react.fluentui.dev/?path=/docs/concepts-developer-browser-support-matrix--page

---

# WIP

The list of polifilled scenarios and what can be removed:

| Scenario | State | Comment | Source |
| --- | --- | --- | --- |
| `display: flex` | 🟢 | ... | https://caniuse.com/?search=display%3A%20flex |
| `display: inline-flex` | 🟢 | ... | https://caniuse.com/?search=display%3A%20inline-flex |
| `flex: *` | 🟢 | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/flex |
| `flex-grow: *` | 🟢 | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow |
| `flex-shrink: *` | 🟢  | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink |
| `flex-basis: *` | 🟢 | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis |
| `align-self: *` | 🟢 | All prefixed scenarios are supported | https://developer.mozilla.org/en-US/docs/Web/CSS/align-self |
| `align-content: *` | 🟢 | All prefixed scenarios are supported | https://developer.mozilla.org/en-US/docs/Web/CSS/align-content |
| `align-items: *` | 🟢 | All prefixed scenarios are supported | https://developer.mozilla.org/en-US/docs/Web/CSS/align-items |
| `justify-content: *` |  🟢 | All prefixed scenarios are supported | https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content |
| `justify-items: *` | 🟢 | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/justify-items |
| `order` | 🟢 | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/order |
| `flex-direction: *` | 🟢 | ... | https://caniuse.com/?search=flex-direction |
| `transform: *` | 🟢 | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/transform |
| `cursor: grab` | 🟢 | ... | https://caniuse.com/?search=cursor%3A%20grab |
| `cursor: image-set()` | 🔴 | Needs to be prefixed | https://caniuse.com/?search=image-set |
| `backface-visibility: *` | 🔴 | Needs to be prefixed due Safari | https://developer.mozilla.org/en-US/docs/Web/CSS/backface-visibility |
| `transition: *` | 🟢 | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/transition |
| `writing-mode: *` | 🟢 | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode |
| `columns*: *` | 🟢 | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/columns |
| `text-size-adjust: *` | 🟢 | Support is limited, prefixing is not needed | https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust |
| `text-decoration: *` | 🟢 | Shorthand is not supported in Safari, but prefixer does not do expansion | https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration |
| `mask:*` | 🔴 | Prefixing is needed | https://caniuse.com/?search=mask |
| `filter:*` | 🟢 | ... | https://developer.mozilla.org/en-US/docs/Web/CSS/filter |
| `position: sticky` | 🟢 | ... | https://caniuse.com/?search=position%3A%20sticky |
| `color-adjust: *` | 🟡 | Propery is "print-color-adjust", can be removed | https://developer.mozilla.org/en-US/docs/Web/CSS/print-color-adjust |
- `box-decoration-break:*`
- `clip-path:*`
- `height:fill-available`
- `width:fit-content`
  - `min-block-size`
  - `width:stretch`
  - `max-height:fit-content`
- `background:image-set`
- `background-clip:text`
- `margin-inline`
- `user-select: *`
- `appearance:*`
- `animation*`
- `grid*`
| `scroll-snap-type` | 🟢 | All browsers in matrix support it | https://caniuse.com/?search=scroll-snap-type | 
| `scroll-margin` | 🟢  | Safari 14.1 has support for these properties | https://caniuse.com/?search=scroll-margin-top  | 
| `tab-size` | 🔴 | Required, native support in Firefox landed in 91 | https://caniuse.com/?search=tab-size |

**Comment by ling1726** [comment]
* inline-grid https://caniuse.com/?search=inline-grid
