### ISSUE TITLE
Griffel DevTools does not works

### ISSUE THREAD

**Issue by stevebeauge** [microsoft/griffel#382]
I'm trying to use Griffel DevTools, but it does not works:

![image](https://github.com/microsoft/griffel/assets/184604/3dee3161-40e3-46d5-bc07-1ab92ad6be6a)

I inspect elements in the page that have Grifel style, but as you can, the dev tools does not understand it.

I guess the extension is loaded, because in the console I can see some traces from the extension.

What am I doing wrong? what's missing?

FYI: 
* In my project, `@fluentui/react-component` version is `9.22.1`. But it also happens on fluentui website
* Issue seen both using Google Chrome `114.0.5735.135 (Build officiel) (64 bits) (cohort: 114_control_135)` and Edge `115.0.1901.151 (Version officielle) beta (64 bits)`
* Working on W11 64bits

Thanks for help

**Comment by layershifter** [comment]
Griffel Devtools do not work for production builds i.e. if you will clone Fluent UI repo and run that Storybook locally it will work like a charm:

<img width="1204" alt="image" src="https://github.com/microsoft/griffel/assets/14183168/ae926aa9-e6f2-40ec-b8b9-296dfdb305a6">

It's hard to say why they don't work in your project, do you have `__GRIFFEL_DEVTOOLS__` on a `Window` object?

<img width="290" alt="image" src="https://github.com/microsoft/griffel/assets/14183168/036c15f5-6d6a-431a-a905-2a0ea3a658e0">

**Comment by stevebeauge** [comment]
No I don't have `__GRIFFEL_DEVTOOLS__` defined.

What is the condition to consider the project as "non production"?

I'm using vite with `mode: 'development'` and I ensure to set the env variable to `NODE_ENV: 'development'`

**Comment by layershifter** [comment]
> What is the condition to consider the project as "non production"?
> 
> I'm using vite with `mode: 'development'` and I ensure to set the env variable to `NODE_ENV: 'development'`

The condition is there, https://github.com/microsoft/griffel/blob/58f328b22560289516c97c45890ff60372dc8cbb/packages/core/src/renderer/createDOMRenderer.ts#L111-L113

Can please you put debugger on this line on your side a check what breaks?

**Comment by stevebeauge** [comment]
I think it won't be possible to use this dev tool if I'm working on a browser extension.

`React dev tools` has the [same issue](https://github.com/facebook/react/issues/20453#issuecomment-744470317).

Basically, the extension won't inject its content script because it's forbidden:

![image](https://github.com/microsoft/griffel/assets/184604/5199dbf7-9e2f-4642-bc7f-aa01dc3510e6)
