### ISSUE TITLE
@container at rule not working

### ISSUE THREAD

**Issue by jvince** [microsoft/griffel#396]
While testing the ` @container ` at rule using the example from the [documentation](https://griffel.js.org/react/api/make-styles#at-rules)  I got the following error:

![Screenshot from 2023-07-18 11-40-55](https://github.com/microsoft/griffel/assets/8256496/447a665e-2b59-456f-9d85-58c78d615e40)

I also tried the following combinations for the ampersand placeholder which didn't yield any results:

- `&@container (max-width: 992px)`
- `& @container (max-width: 992px)`
- `@container (max-width: 992px)&`
- `@container (max-width: 992px) &`

Test project: https://codesandbox.io/s/jovial-darwin-7hr6xg-7hr6xg?file=/src/App.js:361-391

**Comment by layershifter** [comment]
Hey @jvince, it looks that your example uses an outdated version of `@griffel/react`:

- 1.5.6 https://codesandbox.io/s/griffel-container-forked-w3t4w3?file=/src/App.js 🔴 
- 1.5.11 https://codesandbox.io/s/griffel-container-forked-f2htmx?file=/src/App.js ✅

**Comment by jvince** [comment]
@layershifter Thank you for your quick response!

Ahh yes, I see it now. I also forgot to define the containment type.

Solved. Once again thanks for the help @layershifter .

**Comment by mdrichardson** [comment]
@layershifter Can we re-open this? I don't think this is behaving as it should. It seems like some properties get overwritten and others don't.

See: [https://codesandbox.io/s/griffel-container-forked-hfsthh?file=/src/App.js](https://codesandbox.io/s/griffel-container-forked-hfsthh?file=/src/App.js)

There's likely more, but so far I've found that `backgroundColor` and `flexBasis` (both written as `flexBasis` and part of `...shorthands.flex()`).
