### ISSUE TITLE
How to add multiple classes with condition

### ISSUE THREAD

**Issue by tienlx97** [microsoft/griffel#408]
I want to add multiple classes with condition

```tsx

<div className={mergeClasses(active && ['class-A', 'class-B']) />
```

**Comment by layershifter** [comment]
Syntax with arrays is not support and is not planned for implementation.

---

The general recommendation for this case:

```ts
<div className={mergeClasses(active && 'class-A', active && 'class-B') />
```

Nested `mergeClasses` calls are not recommended, but can be also used:

```ts
<div className={mergeClasses(active && mergeClasses('class-A', 'class-B')) />
```
