### ISSUE TITLE
How to combine class strings + griffel atomic classes

### ISSUE THREAD

**Issue by benkeen** [microsoft/griffel#424]
Simple scenario + easy to solve, I just wasn't sure of the best-practice for this use-case. 

My (existing) component accepts a `className` prop which is a string potentially containing potentially multiple classes. My component is using Griffel and constructs its own classes. 

What's the recommended way to combine them?

**Comment by spmonahan** [comment]
I think you want [`mergeClasses()`](https://griffel.js.org/react/api/merge-classes).

I put together an example based on your description: https://codesandbox.io/s/mergeclasses-example-48dk65

**Comment by benkeen** [comment]
Oh! Apologies, I didn't think that method permitted that. Terrific, thanks for the help :)

**Comment by spmonahan** [comment]
Glad it worked!

@layershifter this might be a good example to add to the docs. What do you think?

**Comment by layershifter** [comment]
@spmonahan yes, we should add a note to `mergeClasses()` docs about this (https://griffel.js.org/react/api/merge-classes). @benkeen @spmonahan would you like to submit a PR? 🐱

**Comment by benkeen** [comment]
Sure, np! I can knock something up tonight. :)
