### ISSUE TITLE
Duplicate styles using SSR in Next.js

### ISSUE THREAD

**Issue by Yukioru** [microsoft/griffel#43]
Hello.

When configuring styles in SSR in Next.js, I encountered a problem.
After hydrating the styles - the client also inserts its own `<style>` tags. This results in duplication of styles.

As there is no [SSR documentation](https://github.com/microsoft/griffel/issues/32) yet, I implemented using the source code.

Screenshot: ![image](https://user-images.githubusercontent.com/8497115/154965160-7cc92dd7-9dc5-4df6-b2cc-34d10bb22ae2.png)

```js
static async getInitialProps(ctx) {
  const originalRenderPage = ctx.renderPage;
  const renderer = createDOMRenderer();

  ctx.renderPage = () =>
    originalRenderPage({
      enhanceApp: (App) => {
        return function EnhancedApp(props) {
          return (
            <RendererProvider renderer={renderer}>
              <App {...props} />
            </RendererProvider>
          );
        };
      }
    });

  const documentProps = await NextDocument.getInitialProps(ctx);

  documentProps.styles = (
    <>
      {documentProps.styles}
      {renderToStyleElements(renderer)}
    </>
  );

  return documentProps;
}
```

Reproduced the problem in [CodeSandbox](https://codesandbox.io/s/next-griffel-ssr-fyfy0p?file=/pages/_document.jsx).

Maybe this is not a bug and there is a way to disable client initialisation of already hydrated elements

**Comment by layershifter** [comment]
@Yukioru thanks for the interest and reporting 👍 There are two separate issues actually...

## Proper configuration

We perform rehydration on the client, it's done in `RendererProvider`:
https://github.com/microsoft/griffel/blob/0a94e833bbc3a68276a52774d1de14d39a33635c/packages/react/src/RendererContext.tsx#L36-L38

The difference is in configuration, I updated your CodeSandbox (https://codesandbox.io/s/next-griffel-ssr-forked-2zok5q). In short the same instance of `renderer` should be used, for this `RendererProvider` should be moved to `App`:

```diff
// @document.jsx
     originalRenderPage({
        enhanceApp: (App) => {
          return function EnhancedApp(props) {
            return (
-              <RendererProvider renderer={renderer}>
-                <App {...props} />
+                <App {...props} renderer={renderer} />
-              </RendererProvider>
            );
          };
        }
      });
```

```diff
// @app.jsx
-function App({ Component, pageProps }) {
+function App({ Component, pageProps, renderer }) {
  return (
+    <RendererProvider renderer={renderer || createDOMRenderer()}>
```

#### Before

![image](https://user-images.githubusercontent.com/14183168/154980800-d12c0ba0-db08-424c-9930-b1b8841e055e.png)


#### After

![image](https://user-images.githubusercontent.com/14183168/154980726-fe1591b8-7128-419f-885f-ba1e463a210a.png)


### `makeStaticStyles()` does not support hydration

This was not implemented yet, but should... 🐱 I created a separate #44 to track this.

**Comment by vashek** [comment]
For anyone landing here from a search: there's a **second, distinct** way griffel styles get duplicated under SSR that's specific to the **Next.js App Router**, and the symptom is different enough that it's worth spelling out.

With the App Router you flush styles via `useServerInsertedHTML`. The catch is that **Next calls that callback once per streaming flush**, and `renderToStyleElements(renderer)` returns the renderer's **entire accumulated CSS every time** (it has no delta/clear). So the first copy lands in `<head>` and the **remaining copies stream into `<body>`** — the same stylesheet repeated many times.

Unlike the client-rehydration duplication in the original report, this one is mostly invisible until you **navigate client-side**: the duplicated `<body>` copies (which include `makeResetStyles` base rules) persist after a soft navigation and, sitting after `<head>` at equal specificity, **outrank** the runtime override rules griffel inserts into `<head>` afterwards. Result: `makeStyles` overrides lose to their reset and components snap back to default sizing — but only after a client-side nav, and often on components unrelated to the navigation. A hard reload always looks fine, which makes it maddening to track down.

**Fix** — clear the emitted sheets after each flush so only the delta is emitted:

```tsx
useServerInsertedHTML(() => {
  const styles = renderToStyleElements(renderer);
  renderer.stylesheets = {}; // emit only the per-flush delta; don't re-stream all CSS into <body>
  return <>{styles}</>;
});
```

Clear only `stylesheets`, not `insertionCache`, so already-emitted rules are skipped while new rules from later-resolving subtrees still flush. (This mirrors what styled-components' `clearTag()` does in the [Next.js CSS-in-JS guide](https://nextjs.org/docs/app/guides/css-in-js).)

Quick check: fetch a route without JS and confirm `data-make-styles-rehydration` appears only in `<head>`, never in `<body>`.

It might be worth either documenting this App Router pattern in the [SSR guide](https://griffel.js.org/react/guides/ssr-usage/) (it currently only covers the Pages Router `_document` one-shot case) - PR #995 or adding a dev-mode warning when the same bucket is flushed more than once PR #996.
