### ISSUE TITLE
docs: makeStaticStyles doesn't mention it returns a React hook

### ISSUE THREAD

**Issue by NotWoods** [microsoft/griffel#443]
I've seen a lot of developer confusion around the fact that Griffel creates React hooks. Most developers don't realize it produces hooks. The lint rule helps, but now some developers think Griffel simply creates things that need the name "use" and still aren't hooks.

[`makeStaticStyles`](https://griffel.js.org/react/api/make-static-styles) doesn't mention that it creates a React hook, so some devs on our team were tripped up and assumed it broke the pattern and did not return a React hook.

It should probably also mention if shorthands are OK or not.

**Comment by sanketmp** [comment]
can I do this?

**Comment by layershifter** [comment]
@sanketmp Feel free to submit a PR 👍
