### ISSUE TITLE
Microsoft Learn Video Issue: Simplified Chinese and Traditional Chinese subtitles are reversed

### ISSUE THREAD

**Issue by qoqiyu** [microsoft/griffel#445]
[Learn more?](https://github.com/microsoft/griffel#learn-more) <- here, the [video link](https://learn.microsoft.com/en-us/shows/fluent-ui-insights/fluent-ui-insights-styling?utm_source=github)

In the video linked above, the subtitles for Simplified Chinese and Traditional Chinese are reversed.

![the subtitles for Simplified Chinese and Traditional Chinese are reversed.](https://github.com/microsoft/griffel/assets/48037182/f2a76115-9dba-41cd-8940-6216cc10ce79)

**Comment by layershifter** [comment]
@qoqiyu thanks for reporting, I reported the problem to production team. Will follow up once it's fixed 👍
