### ISSUE TITLE
bug(core): missing vendor prefix (webkit) for background-clip: text

### ISSUE THREAD

**Issue by wfwf1997** [microsoft/griffel#457]
Webkit-based browsers may still need vendor prefix for `background-clip: text` to work properly.

#379 marked the prefix is good to be removed. However, both [caniuse](https://caniuse.com/background-clip-text) and [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip#browser_compatibility) show that the style still needs a vendor prefix for webkit. The style is broken since `@griffel/core` 1.13.0 (including the latest version).

`@griffel/core` 1.14.3:
![image](https://github.com/microsoft/griffel/assets/5110161/d9014036-7eb9-406a-957e-80f5df5fc525)

`@griffel/core` 1.12.2:
![image](https://github.com/microsoft/griffel/assets/5110161/65e6421c-aea4-4acf-9302-af5ccad2a412)

Repro link:
codesandbox: https://codesandbox.io/s/unruffled-edison-8lv8rz

You can switch the dependency version in the left pane. You may want to refresh the preview after changing the version :)

**Comment by layershifter** [comment]
@wfwf1997 Prefixing for that case should be restored, good catch 👍
