### ISSUE TITLE
Add shorthand function for `outline`

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/griffel#50]
Right now there's no shorthand in `@griffer/core` for [`outline`](https://developer.mozilla.org/en-US/docs/web/css/outline)

Although this isn't the main focus border styling method we use in Fluent UI itself, having a shorthand available would be helpful in cases where it's necessary to use `outline`.

### How it should work?

`outline` is CSS shorthand that is expanded to three properties [`outline-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/outline-color), [`outline-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/outline-style), [`outline-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/outline-width).

CSS has variadic handlers for parameters:

```css
/* style */
outline: solid;

/* color | style */
outline: #f66 dashed;

/* style | width */
outline: inset thick;

/* color | style | width */
outline: green solid 3px;
```

But we can't do the same smart thing, proposed API that follows the same CSS order:

```tsx
outline('color') // { outlineColor: 'color' }
outline('color', 'style') // { outlineColor: 'color', outlineStyle: 'style' }
outline('color', 'style', 'width') // { outlineColor: 'color', outlineStyle: 'style', outlineWidth: 'width' }
```

For reference use an existing shorthand function for `borderLeft`:

https://github.com/microsoft/griffel/blob/345719aa1e2a5f2781a049d39e4774205dad502d/packages/core/src/shorthands/borderLeft.ts#L6-L15

**Comment by layershifter** [comment]
@ecraig12345 FYI: I moved this issue from Fluent UI repo to Griffel and added requirements/proposed API to the issue's description.
