### ISSUE TITLE
eslint-plugin: add no-unnecesary-shorthands rule

### ISSUE THREAD

**Issue by Hotell** [microsoft/griffel#507]
based on https://github.com/microsoft/fluentui/pull/30544#discussion_r1489301282

**Feature:**

introduce a new rule named lets say `no-unnecesary-shorthands` which would implement autofixer as well.

This rule should have severity `warn` and it should identify unnecessary shorthand usage within codebase

_Input:_

```
const useStyles = makeResetStyles({
  ...shorthands.border('none'),
  ...shorthands.padding(0),
})
```

_Output:_

```
const useStyles = makeResetStyles({
  border: 'none',
  padding: 0,
})
```

**Comment by layershifter** [comment]
As CSS shorthands are supported now as the most of `shorthands.*()` functions have been deprecated - IMO we don't need such rule anymore.
