### ISSUE TITLE
lint: add lint rule that function returned from `makeStyles()` must have a valid hook name

### ISSUE THREAD

**Issue by spmonahan** [microsoft/griffel#590]
A somewhat common usage pattern I've seen with `makeStyles` is:

```ts
const getStyles = makeStyles(/* */); // "getStyles" should be called "useStyles"

// Later
const styles = conditional ? getStyles() : null; // ❌ React hook called conditionally
```

This is a problem because `getStyles` is really a hook but it does not follow the hook naming convention of starting with "use". This makes it difficult for both code reviewers and linters to spot the misused hook.

**Comment by layershifter** [comment]
@spmonahan that rule already exists, https://github.com/microsoft/griffel/blob/main/packages/eslint-plugin/src/rules/hook-naming.md 🐱

**Comment by spmonahan** [comment]
Excellent!
