### ISSUE TITLE
CSP nonce

### ISSUE THREAD

**Issue by NewFuture** [microsoft/griffel#75]
Hi team, how to set the nonce for CSPpolicy with griffel？

Expect a global window configuration and an API configuration.
Reference to  the mergeStyles https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/README.md#working-with-content-security-policy-csp

**Comment by NewFuture** [comment]
@layershifter Great! 👍

**Comment by layershifter** [comment]
@NewFuture Can you please check #86? Does it solve your problem?
