### ISSUE TITLE
core: Publish `shorthand` as a dedicated package

### ISSUE THREAD

**Issue by SukkaW** [microsoft/griffel#77]
... which would benefit the entire CSS-in-JS community! 

I've [been](https://github.com/robinweser/inline-style-expand-shorthand/pull/34) [creating](https://github.com/robinweser/inline-style-expand-shorthand/pull/32) [PR](https://github.com/robinweser/inline-style-expand-shorthand/pull/33)s toward [inline-style-expand-shorthand](https://github.com/robinweser), which is currently the only shorthand expander the entire CSS-in-JS community has, but none of them has been merged.

**Comment by layershifter** [comment]
@SukkaW it's something that we can consider, after #52 will be merged I will followup on that 👍

**Comment by SukkaW** [comment]
@layershifter 

A friendly ping since #52 has been merged, would you mind starting working on this? I'd expect it is being published as `@griffel/shorthand`.

And I can start working on porting features from [`inline-style-expand-shorthand`](https://github.com/robinweser) to Griffel!

**Comment by layershifter** [comment]
@SukkaW this is not our top priority now, but it will eventually happen.

**Comment by Aloento** [comment]
Request the "flex" shorthands, thanks.

**Comment by layershifter** [comment]
@SukkaW Griffel now has support for CSS shorthands in #531, the most of `shorthands.*()` are now deprecated, we don't plan to publish them.
